name: Update Pull Request for Queue's Number One
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of master
        run: git fetch && :git merge origin/master
